// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnzl0u7IE-TupVhGv4k09VTgtANoGd7z8',
    appId: '1:732924401958:web:16bbca2aa59eb8425009e7',
    messagingSenderId: '732924401958',
    projectId: 'kinderlog-70dfd',
    authDomain: 'kinderlog-70dfd.firebaseapp.com',
    storageBucket: 'kinderlog-70dfd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVghAGdat1D_jLBHblO5-V5qJ7st-NUw8',
    appId: '1:732924401958:android:35756c08bfd6b0ec5009e7',
    messagingSenderId: '732924401958',
    projectId: 'kinderlog-70dfd',
    storageBucket: 'kinderlog-70dfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR9PKqXd5U3vOMtQFOY3St646UbVL6mDM',
    appId: '1:732924401958:ios:bfd1f8fa1b7e80625009e7',
    messagingSenderId: '732924401958',
    projectId: 'kinderlog-70dfd',
    storageBucket: 'kinderlog-70dfd.firebasestorage.app',
    iosBundleId: 'com.example.preschoolAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR9PKqXd5U3vOMtQFOY3St646UbVL6mDM',
    appId: '1:732924401958:ios:bfd1f8fa1b7e80625009e7',
    messagingSenderId: '732924401958',
    projectId: 'kinderlog-70dfd',
    storageBucket: 'kinderlog-70dfd.firebasestorage.app',
    iosBundleId: 'com.example.preschoolAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnzl0u7IE-TupVhGv4k09VTgtANoGd7z8',
    appId: '1:732924401958:web:76ac0d56b6cad4be5009e7',
    messagingSenderId: '732924401958',
    projectId: 'kinderlog-70dfd',
    authDomain: 'kinderlog-70dfd.firebaseapp.com',
    storageBucket: 'kinderlog-70dfd.firebasestorage.app',
  );
}
